# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yB6B_k40YFJNgy9b6L6nGgEJulLBS58v
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.cluster import DBSCAN

iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names

# تحويلها إلى DataFrame للتوضيح
df = pd.DataFrame(X, columns=feature_names)
df['target'] = y
df.head()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

gmm = GaussianMixture(n_components=3, random_state=42)
gmm_labels = gmm.fit_predict(X_scaled)

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=gmm_labels, cmap='viridis', s=50)
plt.title("GMM Clustering on Iris (PCA 2D)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()

n_clusters_gmm = len(np.unique(gmm_labels))
print("Number of clusters formed by GMM:", n_clusters_gmm)

dbscan = DBSCAN(eps=0.6, min_samples=5)
dbscan_labels = dbscan.fit_predict(X_scaled)

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=dbscan_labels, cmap='viridis', s=50)
plt.title("DBSCAN Clustering on Iris (PCA 2D)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()

n_clusters_dbscan = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_outliers = list(dbscan_labels).count(-1)

print("Number of clusters formed by DBSCAN:", n_clusters_dbscan)
print("Number of outliers detected by DBSCAN:", n_outliers)