# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWXq-ruuo3jPTrXNLBlDIJQQaMbRZ9vK
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

data = pd.read_csv("employee_salary_data.csv")

X = data[["YearsExperience", "Age", "WorkingHoursPerWeek"]]
y = data["Salary"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

results = {}

linear_model = LinearRegression()
linear_model.fit(X_train_scaled, y_train)

y_train_pred_linear = linear_model.predict(X_train_scaled)
y_test_pred_linear = linear_model.predict(X_test_scaled)

mse_train_linear = mean_squared_error(y_train, y_train_pred_linear)
mse_test_linear = mean_squared_error(y_test, y_test_pred_linear)

results["Linear Regression"] = [mse_train_linear, mse_test_linear]

print("Linear Regression:")
print(f"Train MSE: {mse_train_linear:.3f}")
print(f"Test MSE: {mse_test_linear:.3f}\n")

alphas = [0.01, 0.1, 1, 10]

for alpha in alphas:
    ridge_model = Ridge(alpha=alpha)
    ridge_model.fit(X_train_scaled, y_train)

    y_train_pred = ridge_model.predict(X_train_scaled)
    y_test_pred = ridge_model.predict(X_test_scaled)

    mse_train = mean_squared_error(y_train, y_train_pred)
    mse_test = mean_squared_error(y_test, y_test_pred)

    results[f"Ridge (α={alpha})"] = [mse_train, mse_test]

    print(f"Ridge (alpha={alpha}): Train MSE={mse_train:.3f}, Test MSE={mse_test:.3f}")

print("\n")

for alpha in alphas:
    lasso_model = Lasso(alpha=alpha)
    lasso_model.fit(X_train_scaled, y_train)

    y_train_pred = lasso_model.predict(X_train_scaled)
    y_test_pred = lasso_model.predict(X_test_scaled)

    mse_train = mean_squared_error(y_train, y_train_pred)
    mse_test = mean_squared_error(y_test, y_test_pred)

    results[f"Lasso (α={alpha})"] = [mse_train, mse_test]

    print(f"Lasso (alpha={alpha}): Train MSE={mse_train:.3f}, Test MSE={mse_test:.3f}")

results_df = pd.DataFrame(results, index=["Train MSE", "Test MSE"]).T

results_df.plot(kind="bar", figsize=(10, 6))
plt.title("MSE Comparison of Linear, Ridge, and Lasso Regression")
plt.xlabel("Model Name")
plt.ylabel("MSE Value")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()